add_lunch_combo eclipse_d2vzw-userdebug
add_lunch_combo eclipse_grouper-userdebug
add_lunch_combo eclipse_manta-userdebug
add_lunch_combo eclipse_spectrum-userdebug
add_lunch_combo eclipse_toro-userdebug
add_lunch_combo eclipse_t0tlte-userdebug
add_lunch_combo eclipse_xt907-userdebug
add_lunch_combo eclipse_xt926-userdebug
