add_lunch_combo eclipse_d2spr-userdebug
add_lunch_combo eclipse_d2vzw-userdebug
add_lunch_combo eclipse_grouper-userdebug
add_lunch_combo eclipse_jfltevzw-userdebug
add_lunch_combo eclipse_manta-userdebug
add_lunch_combo eclipse_toro-userdebug
